---
name: zenon_mqtt
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mqtt_client: ^10.8.0
  flutter_dotenv: ^5.2.1
  jiffy: ^6.3.2
  timer_builder: ^2.0.0
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.31
  provider: ^6.1.2
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  equatable: ^2.0.7
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.26.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  freezed: ^3.0.6
flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - lib/l10n/app_en.arb
    - lib/l10n/app_de.arb
    - lib/l10n/app_cs.arb
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
